### ISSUE TITLE
UTC 고려

### ISSUE THREAD

**Issue by offMomySon** [the-disabledss/goose-server#20]

**Comment by rlarlvy153** [comment]
멀로 할건데?

**Comment by offMomySon** [comment]
select @@global.time_zone, @@session.time_zone;

DB 에 Asia/Seoul 으로 셋팅, LocalDateTime 으로 저장 하면,
LocalDateTime 이 DB time 맞춰서 저장됩니다.

**Comment by rlarlvy153** [comment]
그래서 클라에서 받는건 뭐임?
